name: temp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  logger: ^2.7.0
  riverpod_annotation: ^3.0.0
  rxdart: ^0.27.7
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
